title: notes-jekyll
description: I want to write it down, and for it to be pretty.
baseurl: "/notes-jekyll"
url: ""
repository: vsoch/notes-jekyll
paginate: 28

banner: "/assets/img/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/img/favicon.ico" # site's favicon (icon left side of your page)

# Collections
collections:
  papers:
    output: true
    permalink: /:collection/:path
    collections_dir: papers

# MatJek specific configurations
user: 
  avatar: "/assets/img/logo.png"
  github: "vsoch"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  style: _bibliography/my-ieee.cls
  bibliography: references.bib
